In [8]:

import numpy as np
import pandas as pd
 
#Euclidean Distance
def eucledian(p1,p2):
    dist = np.sqrt(np.sum((p1-p2)**2))
    return dist

#Function to calculate KNN
def predict(x_train, y , x_input, k):
    op_labels = []    
    #Loop through the Datapoints to be classified
    for item in x_input: 
        #Array to store distances
        point_dist = []     
        #Loop through each training Data
        for j in range(len(x_train)): 
            distances = eucledian(x_train[j,:] , item) 
            #Calculating the distance
            point_dist.append(distances)  
        point_dist = np.array(point_dist) 

        #Sorting the array while preserving the index
        #Keeping the first K datapoints
        dist = np.argsort(point_dist)[:k] 

        #Labels of the K datapoints from above
        labels = y[dist] 

        #Majority voting
        vals,counts = np.unique(labels, return_counts=True)
        index = np.argmax(counts)
        lab = vals[index]

        op_labels.append(lab)
 
    return op_labels

In [2]:
filename = '/content/iris.xlsx'
df = pd.read_excel(filename)
df.head()

   sepal_length  sepal_width  petal_length  petal_width     species
0           4.9          3.0           1.4          0.2      setosa
1           4.7          3.2           1.3          0.2      setosa
2           4.6          3.1           1.5          0.2      setosa
3           5.0          3.6           1.4          0.2      setosa
4           7.0          3.2           4.7          1.4  versicolor

In [3]:
y = df['species']
x_train = df.drop('species',axis=1)
x_train = x_train.to_numpy()

data = {'sepal_length':[8.2],'sepal_width':[2.6],'petal_length':[3.2],'petal_width':[1.8] }
x_input = pd.DataFrame(data)
x_input = x_input.to_numpy()

In [9]:
k = [3,5,7]

for i in k:
 label = predict(x_train, y , x_input, 7)
 print(f'\n k = {i}, Predicted label is {label}\n')

 k = 3, Predicted label is ['versicolor']


 k = 5, Predicted label is ['versicolor']


 k = 7, Predicted label is ['versicolor']